### ISSUE TITLE
Yeni girdinin Kaydet butonuna birden fazla basildiginda birden fazla gonderiyor.

### ISSUE THREAD

**Issue by bahadircyildiz** [dusmucitleri/admin#9]
Ornek: Yeni blog bilgileri doldurulduktan sonra kaydet butonuna iki kere basinca o blogdan iki tane uretiyor.

**Comment by kucukkanat** [comment]
Butona basildiktan sonra tablo gorunumune dondugu icin bu sorun ortadan kalkiyor
